### ISSUE TITLE
Roadmap or Code-Release Schedule

### ISSUE THREAD

**Issue by neolinsu** [acsl-technion/lynx#1]
Hi,
After reading Lynx's  paper, I'm very interested in the implement of this non-trivial project. May I have the roadmap or code-release schedule of Lynx?

**Comment by tigercosmos** [comment]
I am also looking forward to its release.

**Comment by marount93** [comment]
Hey all,

First of all, thanks for being interested in the work and in the implementation.
I've uploaded the code to the repository.

The code includes the code that runs on (bf), on the host (host_bf), and example for the light-weight library should be running on GPUs.

note: the code is not perfect since it was going through a lot of optimizations during the experimentations.
